services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - app-network
    restart: always

volumes:
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/recherra/data/wp
      o: bind
  
  
  db_data:
    name: db_data
    driver_opts:
      type: none
      device: /home/recherra/data/mdb
      o: bind

networks:
  app-network:
    driver: bridge
